In [12]:
!pip install yfinance
!pip install seaborn

Requirement already satisfied: yfinance in c:\users\owner\anaconda3\lib\site-packages (0.1.70)
Requirement already satisfied: numpy>=1.15 in c:\users\owner\anaconda3\lib\site-packages (from yfinance) (1.21.6)
Requirement already satisfied: requests>=2.26 in c:\users\owner\anaconda3\lib\site-packages (from yfinance) (2.27.1)
Requirement already satisfied: lxml>=4.5.1 in c:\users\owner\anaconda3\lib\site-packages (from yfinance) (4.8.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\owner\anaconda3\lib\site-packages (from yfinance) (0.0.10)
Requirement already satisfied: pandas>=0.24.0 in c:\users\owner\anaconda3\lib\site-packages (from yfinance) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\owner\anaconda3\lib\site-packages (from pandas>=0.24.0->yfinance) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\owner\anaconda3\lib\site-packages (from pandas>=0.24.0->yfinance) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\owner\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.26->yfinance) (2021.5.30)

WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)

Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
Requirement already satisfied: numpy>=1.15 in c:\users\owner\anaconda3\lib\site-packages (from seaborn) (1.21.6)
Requirement already satisfied: matplotlib>=2.2 in c:\users\owner\anaconda3\lib\site-packages (from seaborn) (3.5.1)
Requirement already satisfied: pandas>=0.23 in c:\users\owner\anaconda3\lib\site-packages (from seaborn) (1.3.5)
Requirement already satisfied: scipy>=1.0 in c:\users\owner\anaconda3\lib\site-packages (from seaborn) (1.7.3)
Requirement already satisfied: packaging>=20.0 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.1.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.4.2)
Requirement already satisfied: cycler>=0.10 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\owner\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.32.0)
Requirement already satisfied: typing-extensions in c:\users\owner\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2->seaborn) (4.2.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\owner\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\owner\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.11.2

WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\owner\anaconda3\lib\site-packages)

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

ModuleNotFoundError: No module named 'seaborn'

In [6]:
# Obtain historical data of a stock 
ticker = 'AAPL'
start = '1997-01-01'
end = '2022-08-30'

yf_obj = yf.Ticker(ticker)
data = yf_obj.history(start=start, end=end)

In [10]:
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1997-01-02,0.161046,0.161999,0.158188,0.160093,143113600,0.0,0.0
1997-01-03,0.161046,0.169623,0.160094,0.165811,119716800,0.0,0.0
1997-01-06,0.134364,0.139843,0.131505,0.136270,1882832000,0.0,0.0
1997-01-07,0.138176,0.139129,0.133411,0.133411,976931200,0.0,0.0
1997-01-08,0.139129,0.140082,0.132458,0.134364,1100131200,0.0,0.0

In [9]:
data.corr()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Open,1.000000,0.999937,0.999917,0.999831,-0.384223,0.087613,0.010911
High,0.999937,1.000000,0.999901,0.999916,-0.383469,0.087124,0.011205
Low,0.999917,0.999901,1.000000,0.999921,-0.385286,0.087704,0.010892
Close,0.999831,0.999916,0.999921,1.000000,-0.384382,0.087507,0.011171
Volume,-0.384223,-0.383469,-0.385286,-0.384382,1.000000,-0.052960,-0.003776
Dividends,0.087613,0.087124,0.087704,0.087507,-0.052960,1.000000,-0.001688
Stock Splits,0.010911,0.011205,0.010892,0.011171,-0.003776,-0.001688,1.000000